# Generated by Django 3.2.20 on 2023-10-03 15:07

import oauth2_provider.generators
import oauth2_provider.models
from django.db import migrations, models


class Migration(migrations.Migration):
    run_before = [
        ("oauth2_provider", "0006_alter_application_client_secret"),
    ]

    dependencies = [
        ("dot_restrict_scopes", "0002_auto_20220207_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="restrictedapplication",
            name="hash_client_secret",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restrictedapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True, default="", help_text="Allowed Post Logout URIs list, space separated"
            ),
        ),
        migrations.AlterField(
            model_name="restrictedapplication",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Hashed on Save. Copy it now if this is a new secret.",
                max_length=255,
            ),
        ),
    ]
