# Generated by Django 3.2.20 on 2023-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dot_restrict_scopes", "0003_auto_20231003_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restrictedapplication",
            name="hash_client_secret",
            field=models.BooleanField(default=True),
        ),
    ]
